[package]
name = "tinyhttp_chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.12"
csv = "1.2.2"
svg = "0.13.1"
# zeroize = "1.6.0"
rand = "0.8.5"
base64 = "0.21.2"
