[package]
name = "pgn_opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = { version = "0.18.0", features = ["cairo-backend", "qt-backend"] }
tiny-skia = "0.5.1"
image = "0.23.14"
